server:
  port: 9080

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: fog-node-consumer
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      profile: dev
      label: master
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
